name = "mypainter-site"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "mypainter-quotes"
database_id = "471d8968-eff9-4d6a-be6b-5525f8b25478"

[[r2_buckets]]
binding = "GALLERY"
bucket_name = "mypainter-gallery"
